### ISSUE TITLE
could not be accessed

### ISSUE THREAD

**Issue by az-aka** [TORO-Server/MarumaSign#4]
便利なmodを開発していただいてありがとうございます。
現在こちらのmodでバグが発生しておりますので問い合わせていただきます。
画像の通りうまく画像が表示されません。
![IMG_2885](https://github.com/TORO-Server/MarumaSign/assets/34262221/f9b688c0-483a-433c-b700-2fc00308608b)

どのようにして修正を行えばいいでしょうか？

こちらの環境です。
Feather 1.20.1,1.20.4
windows11
バージョンは２つ試させていただきました。

また、以前使っており、設置していた看板が突然このエラーがでるようになりました。
入力したコマンドはこちらです。
`/give @p minecraft:oak_sign{BlockEntityTag:{front_text:{messages:['["https://i.imgur"]','[".com/fYvOQfV.jp"]','["eg|0|0|0|1|1|0|"]','["0|0"]']}}}`

マルチプレイ・シングルプレイ問わず事象が再現されましたのでその点も情報共有しておきます。

以上お忙しいとは思いますが、修正していただけると助かります。

**Comment by yui-Kitamura** [comment]
本件、シングルプレイでのクライアントログは以下の通りです：
```log
[11:03:44] [Server thread/INFO]: ［az_aka：az_akaに[オークの看板]を1個与えました］
[11:03:45] [Render thread/WARN]: Failed to load texture: marumasa_sign:textures/misc/loading.png
java.io.FileNotFoundException: marumasa_sign:textures/misc/loading.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079) ~[client-intermediary.jar:?]
	at net.minecraft.class_4668.method_23516(class_4668.java:37) ~[client-intermediary.jar:?]
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.method_22993(FullyBufferedMultiBufferSource.java:147) ~[iris-mc1.20.1-1.6.17.temp.jar:?]
	at net.minecraft.class_761.handler$bmi000$iris$batchedentityrendering$beginTranslucents(class_761.java:3496) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1493) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16) ~[rust-extension-1.0.7.jar:?]
[11:03:47] [Timer-2/WARN]: Failure: https://i.imgur.com/DOc7o5u.png
[11:03:53] [Server thread/INFO]: ［az_aka：天候を晴れに設定しました］
```
```log
[11:05:10] [Server thread/INFO]: ［az_aka：az_akaに[オークの看板]を1個与えました］
[11:05:12] [Timer-2/WARN]: Failure: https://i.imgur.com/fYvOQfV.jpeg
[11:05:18] [Render thread/WARN]: Shader spider could not find uniform named InSize in the specified shader program.
[11:05:18] [Render thread/WARN]: Shader spider could not find uniform named Time in the specified shader program.
```

**Comment by yui-Kitamura** [comment]
imgur以外の画像ソースでは正常に描画されました

**Comment by malken21** [comment]
@fhrk-78 に どのバージョンでは jpeg が読み込めないのか検証してもらいました。

検証環境 : Fabric Loader: 0.15.7 / Minecraft・Fabric API 各バージョン

1.0.0 (pre) : **可能**(ただ`.jpg`ではなくissue投稿者の画像のような`.jpeg`拡張子だと不具合が)
1.1.0 (pre) : **可能**(〃)
1.2.0 (pre) : **可能**(〃)
1.3.0 : **可能**(〃)
1.4.0 : **可能**(〃)
1.5.0 : **可能** (〃)
1.6.0 / 1.20.2 : **可能** (〃)
1.7.0 / 1.20.3 : 不可能
1.8.0 / 1.20.4 : 不可能

時間の都合上、修正する作業ができるのは早くても1週間後になりそうです。

**Comment by az-aka** [comment]
かしこまりました。
ありがとうございます。

**Comment by malken21** [comment]
お待たせしました。
https://github.com/TORO-Server/MarumaSign/releases/tag/v1.8.1
jpegファイルが読み込めるように修正しました。
しかし、imgur にアップロードした画像が読み込めない問題は
修正できていません。

**Comment by malken21** [comment]
https://github.com/TORO-Server/MarumaSign/releases/tag/v1.8.3
HTTPヘッダーの `Accept` を `image/png, image/gif, image/jpeg` に設定したことで、
imgur の画像が読み込めるようになりました。

**Comment by az-aka** [comment]
かしこまりました。
対応いただきありがとうございます。
